# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_co', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repos',
            name='contributors',
            field=models.ManyToManyField(blank=True, null=True, related_name='contributors', to='github_co.User'),
        ),
    ]
